name: "Quarkus ecosystem CI"
on:
  workflow_call:
    inputs:
      ecosystem_ci_repo_path:
        required: true
        description: "Path to the ecosystem CI configuration file in the quarkusio/quarkus-ecosystem-ci repository, e.g. 'quarkiverse-ironjacamar/context.yaml'"
        type: string
      java_version:
        required: false
        description: "Java version to use for the build, e.g. 17 or 21. By default, Java 17 will be used."
        type: number
        default: 17
      quarkus_version_pom_path:
        required: false
        description: "Path to the POM file where the Quarkus version is defined, relative to the repository root. By default, it's set to 'rest-fights/pom.xml'."
        type: string
      quarkus_version_pom_property:
        required: false
        description: "Name of the property in the POM file that defines the Quarkus version. By default, it's set to 'quarkus.platform.version'."
        type: string

  # For this CI to work, ECOSYSTEM_CI_TOKEN needs to contain a GitHub with rights to close the Quarkus issue that the user/bot has opened,
  # while 'ECOSYSTEM_CI_REPO_PATH' needs to be set to the corresponding path in the 'quarkusio/quarkus-ecosystem-ci' repository

env:
  ECOSYSTEM_CI_REPO: quarkusio/quarkus-ecosystem-ci
  ECOSYSTEM_CI_REPO_FILE: context.yaml
  JAVA_VERSION: ${{ inputs.java_version }}

  #########################
  # Repo specific setting #
  #########################

  ECOSYSTEM_CI_REPO_PATH: ${{ inputs.ecosystem_ci_repo_path}}
  QUARKUS_VERSION_POM_PATH: ${{ inputs.quarkus_version_pom_path }}
  QUARKUS_VERSION_POM_PROPERTY: ${{ inputs.quarkus_version_pom_property }}

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  build:
    name: "Build against latest Quarkus snapshot"
    runs-on: ubuntu-latest

    steps:
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          path: current-repo

      - name: Checkout Ecosystem
        uses: actions/checkout@v6
        with:
          repository: ${{ env.ECOSYSTEM_CI_REPO }}
          path: ecosystem-ci

      - name: Invoke Pre Ecosystem Hook (if exists)
        if: ${{ hashFiles('./current-repo/.github/workflows/hooks/pre-quarkus-ecosystem-ci.sh') != '' }}
        run: ./current-repo/.github/workflows/hooks/pre-quarkus-ecosystem-ci.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup and Run Tests
        run: ./ecosystem-ci/setup-and-test
        env:
          ECOSYSTEM_CI_TOKEN: ${{ secrets.ECOSYSTEM_CI_TOKEN }}
          QUARKUS_VERSION_POM_PATH: ${{ env.QUARKUS_VERSION_POM_PATH }}
          QUARKUS_VERSION_POM_PROPERTY: ${{ env.QUARKUS_VERSION_POM_PROPERTY }}

      - name: Invoke Post Ecosystem Hook (if exists)
        if: ${{ hashFiles('./current-repo/.github/workflows/hooks/post-quarkus-ecosystem-ci.sh') != '' }}
        run: ./current-repo/.github/workflows/hooks/post-quarkus-ecosystem-ci.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
